### Build a K Nearest Neighbour model to predict if the value of of a cryptocurrency will go increase or not.

Classification model.

dataset:Yahoo finance API

In [1]:
import tensorflow as tf
import pandas as pd

In [3]:
import yfinance
symbol = "DOGE-USD"
start = "2016-01-01"
end = "2023-06-06"
dataframe = yfinance.download(symbol, start, end)
dataframe

[*********************100%%**********************]  1 of 1 completed


Open      High       Low     Close  Adj Close     Volume
Date                                                                    
2017-11-09  0.001207  0.001415  0.001181  0.001415   0.001415    6259550
2017-11-10  0.001421  0.001431  0.001125  0.001163   0.001163    4246520
2017-11-11  0.001146  0.001257  0.001141  0.001201   0.001201    2231080
2017-11-12  0.001189  0.001210  0.001002  0.001038   0.001038    3288960
2017-11-13  0.001046  0.001212  0.001019  0.001211   0.001211    2481270
...              ...       ...       ...       ...        ...        ...
2023-06-01  0.071662  0.072119  0.070882  0.071492   0.071492  163467169
2023-06-02  0.071490  0.073198  0.071168  0.072612   0.072612  172034498
2023-06-03  0.072610  0.072947  0.072334  0.072671   0.072671  112049190
2023-06-04  0.072672  0.073250  0.072466  0.072471   0.072471  135558595
2023-06-05  0.072475  0.072632  0.064828  0.066573   0.066573  506101788

[2035 rows x 6 columns]

In [4]:
dataframe.info()

<class 'pandas.core.frame.DataFrame'>
DatetimeIndex: 2035 entries, 2017-11-09 to 2023-06-05
Data columns (total 6 columns):
 #   Column     Non-Null Count  Dtype  
---  ------     --------------  -----  
 0   Open       2035 non-null   float64
 1   High       2035 non-null   float64
 2   Low        2035 non-null   float64
 3   Close      2035 non-null   float64
 4   Adj Close  2035 non-null   float64
 5   Volume     2035 non-null   int64  
dtypes: float64(5), int64(1)
memory usage: 111.3 KB


Save to CSV

In [5]:
dataframe.to_csv("doge_2016_2013.csv")

In [7]:
df = pd.read_csv("doge_2016_2013.csv")
df

Date      Open      High       Low     Close  Adj Close     Volume
0     2017-11-09  0.001207  0.001415  0.001181  0.001415   0.001415    6259550
1     2017-11-10  0.001421  0.001431  0.001125  0.001163   0.001163    4246520
2     2017-11-11  0.001146  0.001257  0.001141  0.001201   0.001201    2231080
3     2017-11-12  0.001189  0.001210  0.001002  0.001038   0.001038    3288960
4     2017-11-13  0.001046  0.001212  0.001019  0.001211   0.001211    2481270
...          ...       ...       ...       ...       ...        ...        ...
2030  2023-06-01  0.071662  0.072119  0.070882  0.071492   0.071492  163467169
2031  2023-06-02  0.071490  0.073198  0.071168  0.072612   0.072612  172034498
2032  2023-06-03  0.072610  0.072947  0.072334  0.072671   0.072671  112049190
2033  2023-06-04  0.072672  0.073250  0.072466  0.072471   0.072471  135558595
2034  2023-06-05  0.072475  0.072632  0.064828  0.066573   0.066573  506101788

[2035 rows x 7 columns]

### Data Preprocessing

In [9]:
import numpy as np

In [10]:
# Create classifier columns
# if the next day's price is greater than the current date price, price increase/decrease =1, else=-1

INCREASE = 1

DECREASE = -1

df["price_increase/decrease"] = np.where(df["Close"].shift(-1) > df["Close"],
                                          1,-1)
df

Date      Open      High       Low     Close  Adj Close  \
0     2017-11-09  0.001207  0.001415  0.001181  0.001415   0.001415   
1     2017-11-10  0.001421  0.001431  0.001125  0.001163   0.001163   
2     2017-11-11  0.001146  0.001257  0.001141  0.001201   0.001201   
3     2017-11-12  0.001189  0.001210  0.001002  0.001038   0.001038   
4     2017-11-13  0.001046  0.001212  0.001019  0.001211   0.001211   
...          ...       ...       ...       ...       ...        ...   
2030  2023-06-01  0.071662  0.072119  0.070882  0.071492   0.071492   
2031  2023-06-02  0.071490  0.073198  0.071168  0.072612   0.072612   
2032  2023-06-03  0.072610  0.072947  0.072334  0.072671   0.072671   
2033  2023-06-04  0.072672  0.073250  0.072466  0.072471   0.072471   
2034  2023-06-05  0.072475  0.072632  0.064828  0.066573   0.066573   

         Volume  price_increase/decrease  
0       6259550                       -1  
1       4246520                        1  
2       2231080                       -1  
3       3288960                        1  
4       2481270                       -1  
...         ...                      ...  
2030  163467169                        1  
2031  172034498                        1  
2032  112049190                       -1  
2033  135558595                       -1  
2034  506101788                       -1  

[2035 rows x 8 columns]

In [12]:
X = df.iloc[:,1:4]
X

Open      High       Low
0     0.001207  0.001415  0.001181
1     0.001421  0.001431  0.001125
2     0.001146  0.001257  0.001141
3     0.001189  0.001210  0.001002
4     0.001046  0.001212  0.001019
...        ...       ...       ...
2030  0.071662  0.072119  0.070882
2031  0.071490  0.073198  0.071168
2032  0.072610  0.072947  0.072334
2033  0.072672  0.073250  0.072466
2034  0.072475  0.072632  0.064828

[2035 rows x 3 columns]

In [14]:
X = df.iloc[:, 1:4].values
X

array([[0.001207, 0.001415, 0.001181],
       [0.001421, 0.001431, 0.001125],
       [0.001146, 0.001257, 0.001141],
       ...,
       [0.07261 , 0.072947, 0.072334],
       [0.072672, 0.07325 , 0.072466],
       [0.072475, 0.072632, 0.064828]])

In [15]:
y = df.iloc[:,6].values
y

array([  6259550,   4246520,   2231080, ..., 112049190, 135558595,
       506101788], dtype=int64)

### Split Data into training and testing:

Train-test splitting

In [16]:
from sklearn.model_selection import train_test_split

In [23]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2)

In [24]:
X_train.shape

(1628, 3)

In [25]:
X_test.shape

(407, 3)

In [26]:
y_test.shape

(407,)

In [27]:
y_train.shape

(1628,)

### Scaling the data

In [28]:
from sklearn.preprocessing import StandardScaler

standard_scaler = StandardScaler()

standard_scaler.fit(X_train)

X_train_scaled = standard_scaler.transform(X_train)
X_train_scaled

array([[-0.63906277, -0.62609   , -0.65270008],
       [-0.64475763, -0.63136568, -0.65906973],
       [-0.63067598, -0.61852358, -0.64436162],
       ...,
       [-0.09207716, -0.1060398 , -0.1253738 ],
       [-0.62658984, -0.61211741, -0.64135052],
       [ 0.9636388 ,  0.87332095,  1.05096229]])