In [6]:
import yfinance
import numpy as np
import pandas as pd

In [3]:
symbol = "ETH-USD"
start = "2017-01-01"
end = "2023-09-30"
df= yfinance.download(symbol, start, end)
df

[*********************100%%**********************]  1 of 1 completed


Open         High          Low        Close    Adj Close  \
Date                                                                          
2017-11-09   308.644989   329.451996   307.056000   320.884003   320.884003   
2017-11-10   320.670990   324.717987   294.541992   299.252991   299.252991   
2017-11-11   298.585999   319.453003   298.191986   314.681000   314.681000   
2017-11-12   314.690002   319.153015   298.513000   307.907990   307.907990   
2017-11-13   307.024994   328.415009   307.024994   316.716003   316.716003   
...                 ...          ...          ...          ...          ...   
2023-09-25  1580.747437  1595.844116  1565.025513  1588.322876  1588.322876   
2023-09-26  1588.023193  1598.097778  1580.165527  1593.417236  1593.417236   
2023-09-27  1593.108276  1631.910767  1585.368896  1597.491211  1597.491211   
2023-09-28  1597.671997  1666.024170  1597.294678  1652.882690  1652.882690   
2023-09-29  1652.999878  1687.281250  1648.656494  1667.943848  1667.943848   

                Volume  
Date                    
2017-11-09   893249984  
2017-11-10   885985984  
2017-11-11   842300992  
2017-11-12  1613479936  
2017-11-13  1041889984  
...                ...  
2023-09-25  4394930984  
2023-09-26  3544861160  
2023-09-27  5533036096  
2023-09-28  6658092168  
2023-09-29  5529687537  

[2151 rows x 6 columns]

In [4]:
df.to_csv("eth_2017-2023.csv")

### Data Preprocessing

In [7]:
# Create a new column
BUY = 1

SELL = 0

df["Buy/Sell"] = np.where(df["Close"].shift(-1)>df["Close"],
                          BUY,
                          SELL)

In [8]:
df

Open         High          Low        Close    Adj Close  \
Date                                                                          
2017-11-09   308.644989   329.451996   307.056000   320.884003   320.884003   
2017-11-10   320.670990   324.717987   294.541992   299.252991   299.252991   
2017-11-11   298.585999   319.453003   298.191986   314.681000   314.681000   
2017-11-12   314.690002   319.153015   298.513000   307.907990   307.907990   
2017-11-13   307.024994   328.415009   307.024994   316.716003   316.716003   
...                 ...          ...          ...          ...          ...   
2023-09-25  1580.747437  1595.844116  1565.025513  1588.322876  1588.322876   
2023-09-26  1588.023193  1598.097778  1580.165527  1593.417236  1593.417236   
2023-09-27  1593.108276  1631.910767  1585.368896  1597.491211  1597.491211   
2023-09-28  1597.671997  1666.024170  1597.294678  1652.882690  1652.882690   
2023-09-29  1652.999878  1687.281250  1648.656494  1667.943848  1667.943848   

                Volume  Buy/Sell  
Date                              
2017-11-09   893249984         0  
2017-11-10   885985984         1  
2017-11-11   842300992         0  
2017-11-12  1613479936         1  
2017-11-13  1041889984         1  
...                ...       ...  
2023-09-25  4394930984         1  
2023-09-26  3544861160         1  
2023-09-27  5533036096         1  
2023-09-28  6658092168         1  
2023-09-29  5529687537         0  

[2151 rows x 7 columns]

In [10]:
y = df["Buy/Sell"].values
y

array([0, 1, 0, ..., 1, 1, 0])

In [11]:
X = df[["High", "Low", "Open", "Close", "Volume"]].values
X

array([[3.29451996e+02, 3.07056000e+02, 3.08644989e+02, 3.20884003e+02,
        8.93249984e+08],
       [3.24717987e+02, 2.94541992e+02, 3.20670990e+02, 2.99252991e+02,
        8.85985984e+08],
       [3.19453003e+02, 2.98191986e+02, 2.98585999e+02, 3.14681000e+02,
        8.42300992e+08],
       ...,
       [1.63191077e+03, 1.58536890e+03, 1.59310828e+03, 1.59749121e+03,
        5.53303610e+09],
       [1.66602417e+03, 1.59729468e+03, 1.59767200e+03, 1.65288269e+03,
        6.65809217e+09],
       [1.68728125e+03, 1.64865649e+03, 1.65299988e+03, 1.66794385e+03,
        5.52968754e+09]])

#### Train-test Split

In [12]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2)
X_train.shape

(1720, 5)

In [13]:
y_train.shape

(1720,)

In [15]:
X_test.shape, y_test.shape

((431, 5), (431,))

In [22]:
import catboost
from catboost import CatBoostClassifier
model = CatBoostClassifier(iterations = 50, learning_rate =0.1)
model.fit(X_train, y_train)
model.is_fitted()

0:	learn: 0.6918485	total: 2.06ms	remaining: 101ms
1:	learn: 0.6907475	total: 4.01ms	remaining: 96.4ms
2:	learn: 0.6899650	total: 5.86ms	remaining: 91.9ms
3:	learn: 0.6891220	total: 7.69ms	remaining: 88.5ms
4:	learn: 0.6889599	total: 9.24ms	remaining: 83.2ms
5:	learn: 0.6881267	total: 11.2ms	remaining: 82.4ms
6:	learn: 0.6878390	total: 13ms	remaining: 79.8ms
7:	learn: 0.6871923	total: 14.5ms	remaining: 76.2ms
8:	learn: 0.6866478	total: 16.2ms	remaining: 73.6ms
9:	learn: 0.6858782	total: 17.7ms	remaining: 70.8ms
10:	learn: 0.6853919	total: 19.3ms	remaining: 68.5ms
11:	learn: 0.6849255	total: 20.9ms	remaining: 66.2ms
12:	learn: 0.6844436	total: 23ms	remaining: 65.4ms
13:	learn: 0.6842524	total: 24.6ms	remaining: 63.3ms
14:	learn: 0.6834557	total: 26.2ms	remaining: 61.1ms
15:	learn: 0.6828166	total: 28.3ms	remaining: 60.1ms
16:	learn: 0.6823950	total: 30.4ms	remaining: 59ms
17:	learn: 0.6820646	total: 33ms	remaining: 58.6ms
18:	learn: 0.6812327	total: 35.4ms	remaining: 57.7ms
19:	learn: 0

True

### Make Predictions

In [23]:
models_predictions = model.predict(X_test)
models_predictions

array([1, 1, 1, 1, 1, 1, 0, 1, 1, 1, 0, 0, 0, 1, 1, 1, 0, 0, 0, 1, 1, 0,
       0, 1, 1, 0, 1, 1, 0, 1, 1, 1, 0, 0, 1, 1, 0, 0, 0, 1, 0, 1, 0, 1,
       1, 1, 1, 1, 1, 0, 1, 1, 0, 1, 1, 0, 1, 1, 1, 1, 0, 1, 0, 0, 1, 1,
       0, 1, 1, 1, 1, 1, 0, 0, 1, 0, 1, 0, 1, 0, 1, 0, 0, 1, 1, 0, 0, 0,
       0, 0, 1, 0, 1, 0, 0, 1, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1,
       0, 0, 0, 0, 1, 0, 0, 1, 0, 0, 0, 0, 1, 0, 0, 1, 1, 0, 0, 0, 1, 0,
       0, 0, 0, 0, 0, 1, 1, 0, 0, 0, 0, 0, 1, 0, 0, 1, 0, 0, 0, 0, 1, 1,
       1, 1, 0, 1, 1, 1, 1, 1, 0, 1, 0, 0, 0, 0, 0, 0, 0, 1, 0, 1, 0, 1,
       0, 1, 1, 0, 1, 1, 1, 0, 1, 1, 1, 0, 0, 1, 0, 1, 0, 1, 0, 0, 0, 1,
       1, 0, 1, 1, 1, 0, 0, 1, 0, 0, 1, 0, 1, 0, 0, 0, 1, 0, 0, 1, 1, 1,
       1, 1, 1, 0, 0, 1, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 1, 0, 0, 1, 1, 1, 0, 1, 0, 1, 1, 1, 1, 0, 1, 1, 0, 0, 0,
       1, 1, 0, 1, 1, 1, 1, 1, 0, 0, 1, 0, 1, 0, 0, 1, 0, 1, 1, 1, 0, 0,
       1, 1, 0, 1, 0, 0, 0, 1, 0, 1, 0, 1, 1, 1, 0,

In [24]:
model.score(X_test, y_test)

0.5127610208816705